# Linear Algebra: Basics

In [2]:
using LinearAlgebra
using Plots

## Vectors

In [3]:
v1 = [1.0, 0, -2]

3-element Vector{Float64}:
  1.0
  0.0
 -2.0

## Matrices

In [5]:
A = [1.0 2; 3 4]

2×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0

In [4]:
A = [1.0 2
    3 4]

2×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0

In [6]:
zeros(2, 2)

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

In [7]:
ones(Int64, 2, 4)

2×4 Matrix{Int64}:
 1  1  1  1
 1  1  1  1

In [8]:
Diagonal([1, 2, 3, 4])

4×4 Diagonal{Int64, Vector{Int64}}:
 1  ⋅  ⋅  ⋅
 ⋅  2  ⋅  ⋅
 ⋅  ⋅  3  ⋅
 ⋅  ⋅  ⋅  4

In [10]:
Bidiagonal([1, 2, 3, 4], [7, 7, 7], :L)

4×4 Bidiagonal{Int64, Vector{Int64}}:
 1  ⋅  ⋅  ⋅
 7  2  ⋅  ⋅
 ⋅  7  3  ⋅
 ⋅  ⋅  7  4

In [11]:
2*I   # = UniformScaling(2)

UniformScaling{Int64}
2*I

In [12]:
A + 2*I

2×2 Matrix{Float64}:
 3.0  2.0
 3.0  6.0

In [13]:
eye(n) = Diagonal(ones(n))  # Better than Matrix(1.0*I, (n, n))
eye(3)

3×3 Diagonal{Float64, Vector{Float64}}:
 1.0   ⋅    ⋅ 
  ⋅   1.0   ⋅ 
  ⋅    ⋅   1.0

In [14]:
A = [1.0 2; 3 4]
block_matrix = [A zeros(2, 2); zeros(2, 2) eye(2)]

4×4 SparseArrays.SparseMatrixCSC{Float64, Int64} with 6 stored entries:
 1.0  2.0   ⋅    ⋅ 
 3.0  4.0   ⋅    ⋅ 
  ⋅    ⋅   1.0   ⋅ 
  ⋅    ⋅    ⋅   1.0

In [16]:
Symmetric(A, :U)

2×2 Symmetric{Float64, Matrix{Float64}}:
 1.0  2.0
 2.0  4.0

In [17]:
UpperTriangular(A)

2×2 UpperTriangular{Float64, Matrix{Float64}}:
 1.0  2.0
  ⋅   4.0

<img src=img-3.png>

In [18]:
n = 5
function Dirichlet(n)
    D = Bidiagonal(-ones(n-1), ones(n-2), :U)
    D = [D [zeros(n - 2)..., 1.0]]
    return D
end
Dirichlet(5)

4×5 SparseArrays.SparseMatrixCSC{Float64, Int64} with 8 stored entries:
 -1.0   1.0    ⋅     ⋅    ⋅ 
   ⋅   -1.0   1.0    ⋅    ⋅ 
   ⋅     ⋅   -1.0   1.0   ⋅ 
   ⋅     ⋅     ⋅   -1.0  1.0

## Basic Functions and Operations

In [19]:
v1 = [1.0, 0, -2]
v2 = [3.0, 2, 1]

3-element Vector{Float64}:
 3.0
 2.0
 1.0

In [20]:
v1 * v2     # Wrong

LoadError: MethodError: no method matching *(::Vector{Float64}, ::Vector{Float64})
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at operators.jl:560
  *(::StridedMatrix{T}, ::StridedVector{S}) where {T<:Union{Float32, Float64, ComplexF32, ComplexF64}, S<:Real} at /builddir/build/BUILD/julia-1.6.5/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/matmul.jl:44
  *(::StridedVecOrMat{T} where T, ::Adjoint{var"#s814", var"#s813"} where {var"#s814", var"#s813"<:LinearAlgebra.LQPackedQ}) at /builddir/build/BUILD/julia-1.6.5/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/lq.jl:254
  ...

In [21]:
v1 .* v2    # Element-wise product

3-element Vector{Float64}:
  3.0
  0.0
 -2.0

In [22]:
dot(v1, v2)     # Inner product = v1' * v2

1.0

In [23]:
c1 = [1+im 0]
dot(c1, c1)     # = c1' * c1

2 + 0im

In [24]:
println(length(v1))
println(size(A))

println(sum(v1))
# println(sum(A))

println(norm(v1))
# println(norm(A))      # Frobenius norm = sqrt(sum(A.^2))

println(diag(A))
println(sum(diag(A)))    # Trace of A

3
(2, 2)
-1.0
2.23606797749979
[1.0, 4.0]
5.0


## "Try Not To Use" Functions

In [25]:
det(A)  # Who needs it anyway

-2.0

In [26]:
inv(A)  # You need it for sure but you are not going to need it anymore

2×2 Matrix{Float64}:
 -2.0   1.0
  1.5  -0.5

In [27]:
pinv(A)     # Pseudoinverse (or Moore-Penrose inverse) and it's even worse

2×2 Matrix{Float64}:
 -2.0   1.0
  1.5  -0.5